service: serverless-with-webpack

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  stage: dev

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Load our secret environment variables based on the current stage.
  # Fallback to default if it is not in prod.
  environment: ${file(env.yml):${self:custom.stage}, file(env.yml):default}
  webpackIncludeModules: true
  webpackPackager: "yarn"
  serverless-offline:
    port: 8000

package:
  individually: true

functions:
  api:
    handler: src/api.serverless
    events:
      - http:
          method: GET
          path: /{any+}
